
Server:
  port: 9004
  
spring:
  datasource:
    url: jdbc:postgresql://pega2008usf.cs6hpnnbc4rq.us-east-2.rds.amazonaws.com/postgres
    username: 'davemd'
    password: 'ILoveJava'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: shapes-four
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${string.application.name}:${random.value}